# Generated by Django 2.2.4 on 2020-04-18 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dmarket', '0002_auto_20200410_1916'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vremy_market',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(max_length=200, verbose_name='Ведите время в минутах')),
            ],
            options={
                'verbose_name': 'Время повторения запроса',
                'verbose_name_plural': 'Время повторения запроса',
                'db_table': 'Vremy_market',
            },
        ),
        migrations.AlterField(
            model_name='tovar_market',
            name='kol',
            field=models.CharField(help_text='2', max_length=30, verbose_name='Порог$'),
        ),
    ]
