# Generated by Django 2.2.4 on 2020-04-20 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dmarket', '0003_auto_20200418_1444'),
    ]

    operations = [
        migrations.AddField(
            model_name='tovar_market',
            name='paymin',
            field=models.CharField(default=20, help_text='45', max_length=30, verbose_name='Минимальная цена снижения'),
            preserve_default=False,
        ),
    ]
